CREATE TABLE USERS
(
	USER_ID              INTEGER AUTO_INCREMENT,
	NAME                 VARCHAR(50) NOT NULL,
	TITLE                VARCHAR(100) NULL,
	LOGIN_ID             VARCHAR(50) NULL,
	PASSWORD             VARCHAR(50) NULL,
	PRIMARY KEY (USER_ID)
);